name: Build Android APK (TWA)

on:
  push:
    branches: [ android-apk ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      - name: Generate TWA project
        shell: bash
        run: |
          mkdir -p android-twa
          echo "JAVA_HOME=$JAVA_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          # Run Bubblewrap non-interactively; provide JDK path and auto-answer 'n' to any install prompts.
          yes n | bubblewrap init \
            --manifest=public/manifest.webmanifest \
            --directory=android-twa \
            --skipPwaValidation \
            --fallbackType=webapp \
            --packageId=com.itchyfeetleech.groceryhelper \
            --name="GroceryHelper" \
            --launcherName="GroceryHelper" \
            --jdkPath="$JAVA_HOME"

      - name: Build debug APK
        working-directory: android-twa
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: groceryhelper-debug-apk
          path: android-twa/app/build/outputs/apk/debug/app-debug.apk
