name: Build Android APK (TWA)

on:
  push:
    branches: [ android-apk ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      - name: Configure Bubblewrap (JDK & Android SDK)
        shell: bash
        run: |
          mkdir -p "$HOME/.bubblewrap"
          cat > "$HOME/.bubblewrap/config.json" << JSON
          { "jdkPath": "$JAVA_HOME", "androidSdkPath": "$ANDROID_SDK_ROOT" }
          JSON

      - name: Generate/Update Android project from TWA manifest
        shell: bash
        run: |
          npx @bubblewrap/cli update \
            --skipVersionUpgrade \
            --directory android-twa \
            --manifest android-twa/twa-manifest.json

      - name: Build debug APK
        working-directory: android-twa
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: groceryhelper-debug-apk
          path: android-twa/app/build/outputs/apk/debug/app-debug.apk
